config/routes.rb
Rails.application.routes.draw do
  resources :tasks

  root 'tasks#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :all_tasks, only: [:index, :create, :update, :destroy]
  before_action :set_task, only: [:edit, :update, :destroy, :destroy]

  # index and show actions removed

  def new
    @task = Task.new
  end

  def create
    @task  = Task.create(task_params)
  end

  def update
     @task.update(task_params) 
  end

  def destroy
    @task.destroy
  end

  private

    def all_tasks
      @tasks = Task.all
    end

    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:description, :deadline)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="container">
      <%= yield %>
   </div>

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task, remote: true do |f|   %>
  <div class="form-group">
    <%= f.text_area  :description, placeholder: "Describe your task!", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_field :deadline, id: "datetimepicker1", placeholder: "When's it due?", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.button :Submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div class="col-md-12">
  <div class="well">
    <h3><%= task.description %></h3>
    <p><%= task.deadline %></p>
    <p class="pull-right">
      <%= link_to "Edit", edit_task_path(task), remote: true %>	  
      <%= link_to "Delete", task, remote: true, method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
  </div>
</div>

app/views/tasks/create.js.erb
$('#tasks').html("<%= j (render @tasks) %>");
$('#task-form').slideUp(350);

app/views/tasks/destroy.js.erb
$('#tasks').html("<%= j (render @tasks) %>");

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/edit.js.erb
$('#task-form').html("<%= j (render 'form') %>");
$('#task-form').slideDown(350);
<%= render 'datetimepicker' %>

app/views/tasks/index.html.erb
<div class="row">
  <div class="col-md-3">
      <%= link_to new_task_path, remote: true do %>
          <button class="btn btn-default"><span class="glyphicon glyphicon-plus"></span> Add Task </button>
      <% end %>

      <div id="task-form" style="display:none;"></div> 
  </div>

  <div class="col-md-8"> 
    <h2>Katie's Tasks</h2>
    <div id="tasks">
      <div class="row">
        <%= render @tasks %>
      </div>
    </div>
  </div>

</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/new.js.erb
$('#task-form').html("<%= j (render 'form') %>");
$('#task-form').slideDown(350);

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @task.deadline %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/update.js.erb
$('#task-form').html("<%= j (render 'form') %>");
$('#task-form').slideDown(350);